name: Build UI 

on: 
  push:
   branches-ignore:
    - master
    - release
  pull_request:
   branches:
    - master
    - release

env:
  DOTNET_LOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build-windows_ui:
    runs-on: windows-latest
    name: Windows Build (UI)
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources
      - name: Restore Dependencies
        run: dotnet restore src/Cyber.Mods.UI/Cyber.Mods.UI.csproj
      - name: Build MAUI Windows
        run: dotnet build src/Cyber.Mods.UI/Cyber.Mods.UI.csproj -c Release --no-restore